import type { AuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import { prismaEdge } from "@/lib/prisma-edge"; // Assuming this correctly initializes Prisma
import * as bcrypt from "bcryptjs"; // Import bcryptjs

// Assuming Role enum is generated by Prisma and available via @prisma/client
import type { Role } from "@prisma/client";

const prisma = prismaEdge;

export const authOptions: AuthOptions = {
  secret: process.env.NEXTAUTH_SECRET,
  session: { strategy: "jwt", maxAge: 60 * 60 }, // 1 hour
  jwt: { maxAge: 60 * 60 }, // 1 hour
  pages: { signIn: "/login" },
  providers: [
    CredentialsProvider({
      name: "Credentials",
      credentials: {
        name: { label: "Nama", type: "text" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        if (!credentials?.name || !credentials.password) {
          // Return null to indicate authentication failure
          return null;
        }

        // In a real application, you might want to add more robust logging
        // const start = Date.now();
        const user = await prisma.user.findUnique({
          where: { name: credentials.name },
          select: {
            id: true,
            name: true,
            email: true,
            password: true, // Select the hashed password
            role: true,
          },
        });
        // console.log("Login DB duration:", Date.now() - start, "ms");

        if (!user) {
          // User not found
          return null;
        }

        // Compare the provided password with the hashed password from the database
        const isPasswordValid = await bcrypt.compare(
          credentials.password,
          user.password
        );

        if (!isPasswordValid) {
          // Passwords do not match
          return null;
        }

        // Return user object if authentication is successful
        return {
          id: user.id,
          name: user.name,
          email: user.email,
          role: user.role as Role, // Ensure type consistency
        };
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
        token.role = user.role; // Cast to any to access custom property
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user) {
        session.user.id = token.id as string;
        session.user.role = token.role as Role;
      }
      return session;
    },
  },
};
